name: Build and test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  security_tests:
    runs-on: ubuntu-latest

    steps:
    - name: Clone the GitHub repository on the machine
      uses: actions/checkout@v4
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
    - name: Install program dependencies
      run: npm install
    - name: Run npm security tests
      run: npm audit

      
  build_test:
    runs-on: ubuntu-latest
    needs: security_tests

    steps:
    - name: Clone the GitHub repository on the machine
      uses: actions/checkout@v4
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
    - name: Install program dependencies
      run: npm install
    - name: Run integration tests
      run: npm run test

  